# Generated by Django 2.0.4 on 2018-05-11 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=25)),
                ('issue_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField(max_length=2)),
                ('rate', models.IntegerField(max_length=2)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ttype', models.CharField(max_length=6)),
                ('amount', models.IntegerField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.Account')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.Users'),
        ),
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.Users'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.Users'),
        ),
    ]
