# Generated by Django 2.0.4 on 2018-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0002_auto_20180513_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='tenure',
            field=models.IntegerField(),
        ),
    ]
